language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip
script:
  - make build
  - make test
install:
  - go get github.com/op/go-logging
  - go get github.com/miekg/dns
  - go get golang.org/x/net/http2

notifications:
  email:
    recipients:
      - shell909090@gmail.com
    on_success: never
    on_failure: change